# Generated by Django 6.0.7 on 2026-07-25 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('business', '商务负责人'), ('technical', '技术负责人'), ('both', '商务与技术兼任'), ('other', '其他岗位')], default='other', max_length=20, verbose_name='岗位类型')),
                ('nickname', models.CharField(blank=True, max_length=50, verbose_name='员工昵称')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='员工账号')),
            ],
            options={
                'verbose_name': '员工档案',
                'verbose_name_plural': '员工档案',
            },
        ),
    ]
