# Generated by Django 6.0.7 on 2026-07-28 16:08

import customers.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_project_followuptask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TomorrowItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='事项标题')),
                ('note', models.TextField(blank=True, verbose_name='补充说明')),
                ('planned_date', models.DateField(default=customers.models.default_tomorrow_date, verbose_name='计划日期')),
                ('is_completed', models.BooleanField(default=False, verbose_name='已完成')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tomorrow_items', to=settings.AUTH_USER_MODEL, verbose_name='所属员工')),
            ],
            options={
                'verbose_name': '个人明日事项',
                'verbose_name_plural': '个人明日事项',
                'ordering': ('is_completed', 'created_at'),
            },
        ),
    ]
