# Generated by Django 6.0.7 on 2026-08-10 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_project_types(apps, schema_editor):
    ProjectType = apps.get_model('customers', 'ProjectType')
    Project = apps.get_model('customers', 'Project')
    types = {
        name: ProjectType.objects.get_or_create(name=name)[0]
        for name in ('道路', '回填', '水利', '护坡', '抑尘剂')
    }
    keyword_map = (
        ('道路', ('道路', '步道', '地坪', '地面')),
        ('回填', ('回填', '填方')),
        ('水利', ('水利', '河道', '水库', '堤坝')),
        ('护坡', ('护坡', '边坡')),
        ('抑尘剂', ('抑尘', '防尘')),
    )
    for project in Project.objects.filter(project_type__isnull=True):
        text = f'{project.name} {project.plan}'
        for type_name, keywords in keyword_map:
            if any(keyword in text for keyword in keywords):
                project.project_type = types[type_name]
                project.save(update_fields=('project_type',))
                break


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_sync_followup_assignees'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='项目类型名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='可用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '项目类型',
                'verbose_name_plural': '项目类型',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ProgressUpdateReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(blank=True, null=True, verbose_name='最后查看时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress_update_read_state', to=settings.AUTH_USER_MODEL, verbose_name='员工账号')),
            ],
            options={
                'verbose_name': '进度更新阅读状态',
                'verbose_name_plural': '进度更新阅读状态',
            },
        ),
        migrations.CreateModel(
            name='ProjectProgressUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='进度更新')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_progress_updates', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='customers.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '项目进度更新',
                'verbose_name_plural': '项目进度更新',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='customers.projecttype', verbose_name='项目类型'),
        ),
        migrations.RunPython(seed_project_types, migrations.RunPython.noop),
    ]
