# Generated by Django 6.0.7 on 2026-08-10 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_projecttype_progressupdatereadstate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='business_level',
            field=models.PositiveSmallIntegerField(default=1, help_text='1-5级，数字越大，在进度汇总中排序越靠前。', verbose_name='商务等级'),
        ),
        migrations.CreateModel(
            name='VisitorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(verbose_name='来访日期')),
                ('visitor_count', models.PositiveSmallIntegerField(default=1, verbose_name='来访人数')),
                ('contact_name', models.CharField(blank=True, max_length=100, verbose_name='来访联系人')),
                ('purpose', models.CharField(max_length=200, verbose_name='来访目的')),
                ('notes', models.TextField(blank=True, verbose_name='接待记录')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_visitor_records', to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_records', to='customers.customer', verbose_name='关联客资')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_visitor_records', to=settings.AUTH_USER_MODEL, verbose_name='接待负责人')),
            ],
            options={
                'verbose_name': '客户来访记录',
                'verbose_name_plural': '客户来访记录',
                'ordering': ('-visit_date', '-id'),
            },
        ),
    ]
