# Generated by Django 6.0.7 on 2026-08-10 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_employeeprofile_business_level_visitorrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprogressupdate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改时间'),
        ),
    ]
