# Generated by Django 6.0.7 on 2026-08-10 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_projectprogressupdate_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressUpdateReadReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='已读时间')),
                ('progress_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='customers.projectprogressupdate', verbose_name='进度更新')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_update_read_receipts', to=settings.AUTH_USER_MODEL, verbose_name='阅读账号')),
            ],
            options={
                'verbose_name': '进度更新已读记录',
                'verbose_name_plural': '进度更新已读记录',
                'ordering': ('-read_at', '-id'),
                'constraints': [models.UniqueConstraint(fields=('user', 'progress_update'), name='unique_progress_update_read_receipt')],
            },
        ),
    ]
