# Generated by Django 6.0.7 on 2026-08-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_schemecalculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorrecord',
            name='remarks',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
    ]
