# Generated by Django 6.0.7 on 2026-08-27 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def add_default_customer_identity(apps, schema_editor):
    Customer = apps.get_model('customers', 'Customer')
    PartnershipIdentity = apps.get_model('customers', 'PartnershipIdentity')
    PartnershipIdentity.objects.bulk_create([
        PartnershipIdentity(customer_id=customer_id, identity_type='customer')
        for customer_id in Customer.objects.values_list('id', flat=True).iterator()
    ], ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0019_interval_progress_and_material_experiment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='commercial_notes',
            field=models.TextField(blank=True, verbose_name='商务信息'),
        ),
        migrations.AddField(
            model_name='project',
            name='contract_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='合同金额'),
        ),
        migrations.AddField(
            model_name='project',
            name='quoted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='报价金额'),
        ),
        migrations.AddField(
            model_name='project',
            name='owners_inherit_customer',
            field=models.BooleanField(default=True, help_text='关闭后，该项目负责人不再随客户级默认负责人变更。', verbose_name='负责人沿用客户默认值'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='role',
            field=models.CharField(choices=[('business', '商务负责人'), ('technical', '技术负责人'), ('both', '商务与技术兼任'), ('agent', '代理商账号'), ('other', '其他岗位')], default='other', max_length=20, verbose_name='岗位类型'),
        ),
        migrations.CreateModel(
            name='BusinessAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='附件名称')),
                ('category', models.CharField(choices=[('general', '常规附件'), ('contract', '合同附件'), ('authorization', '授权/代理协议'), ('project', '项目资料')], default='general', max_length=20, verbose_name='附件类型')),
                ('file_url', models.CharField(max_length=500, verbose_name='文件地址')),
                ('is_sensitive', models.BooleanField(default=False, verbose_name='敏感附件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_attachments', to='customers.customer', verbose_name='客户主体')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_attachments', to='customers.project', verbose_name='关联项目')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_business_attachments', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '业务附件',
                'verbose_name_plural': '业务附件',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='AgencyAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('province', '省级代理'), ('city', '市级代理'), ('district', '区县代理')], max_length=20, verbose_name='代理级别')),
                ('province', models.CharField(max_length=50, verbose_name='授权省份')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='授权城市')),
                ('district', models.CharField(blank=True, max_length=50, verbose_name='授权区县')),
                ('is_exclusive', models.BooleanField(default=False, verbose_name='独家授权')),
                ('product_scope', models.CharField(max_length=300, verbose_name='授权产品或业务范围')),
                ('effective_date', models.DateField(verbose_name='生效日期')),
                ('expiry_date', models.DateField(verbose_name='到期日期')),
                ('agreement_status', models.CharField(choices=[('intent', '意向'), ('negotiating', '谈判中'), ('pending', '待签约'), ('active', '已签约/履约中'), ('renewed', '已续约'), ('terminated', '已终止'), ('expired', '已到期')], default='intent', max_length=20, verbose_name='协议状态')),
                ('agreement_number', models.CharField(blank=True, max_length=100, verbose_name='协议编号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agency_authorizations', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_authorizations', to='customers.customer', verbose_name='代理主体')),
                ('viewers', models.ManyToManyField(blank=True, related_name='agency_authorizations', to=settings.AUTH_USER_MODEL, verbose_name='可查看该授权范围的代理账号')),
            ],
            options={
                'verbose_name': '区域代理授权',
                'verbose_name_plural': '区域代理授权',
                'ordering': ('expiry_date', 'province', 'city', 'district', 'id'),
                'indexes': [models.Index(fields=['province', 'city', 'district'], name='customers_a_provinc_10c586_idx'), models.Index(fields=['agreement_status', 'expiry_date'], name='customers_a_agreeme_f7381d_idx')],
            },
        ),
        migrations.CreateModel(
            name='BusinessContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='合同名称')),
                ('contract_number', models.CharField(blank=True, max_length=100, verbose_name='合同编号')),
                ('status', models.CharField(choices=[('intent', '意向'), ('negotiating', '谈判'), ('pending', '待签约'), ('active', '已签约/履约中'), ('expiring', '即将到期'), ('expired', '已到期'), ('renewed', '已续约'), ('terminated', '已终止')], default='intent', max_length=20, verbose_name='合同状态')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='合同金额')),
                ('signed_date', models.DateField(blank=True, null=True, verbose_name='签约日期')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='生效日期')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='到期日期')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_business_contracts', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_contracts', to='customers.customer', verbose_name='客户主体')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_contracts', to='customers.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '商务合同',
                'verbose_name_plural': '商务合同',
                'ordering': ('expiry_date', '-updated_at', 'id'),
                'indexes': [models.Index(fields=['status', 'expiry_date'], name='customers_b_status_596111_idx')],
            },
        ),
        migrations.CreateModel(
            name='PartnershipIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_type', models.CharField(choices=[('customer', '客户'), ('signed_customer', '签约客户'), ('provincial_agent', '省级代理'), ('city_agent', '市级代理'), ('district_agent', '区县代理'), ('partner', '合伙人'), ('channel_partner', '渠道合作方'), ('technical_partner', '技术合作方')], max_length=40, verbose_name='合作身份')),
                ('is_active', models.BooleanField(default=True, verbose_name='有效')),
                ('notes', models.CharField(blank=True, max_length=300, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_partnership_identities', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnership_identities', to='customers.customer', verbose_name='客户主体')),
            ],
            options={
                'verbose_name': '合作身份',
                'verbose_name_plural': '合作身份',
                'ordering': ('identity_type', 'id'),
                'constraints': [models.UniqueConstraint(fields=('customer', 'identity_type'), name='unique_customer_partnership_identity')],
            },
        ),
        migrations.RunPython(add_default_customer_identity, migrations.RunPython.noop),
    ]
