# Generated by Django 6.0.7 on 2026-09-07 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0029_customer_wechat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tomorrowitem',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_items', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='tomorrowitem',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='已取消'),
        ),
        migrations.AddField(
            model_name='tomorrowitem',
            name='kind',
            field=models.CharField(choices=[('personal', '个人事项'), ('appointment', '客户预约'), ('project', '项目事项')], default='personal', max_length=20, verbose_name='事项类型'),
        ),
        migrations.AddField(
            model_name='tomorrowitem',
            name='planned_time',
            field=models.TimeField(blank=True, null=True, verbose_name='安排时间（空为全天）'),
        ),
        migrations.AddField(
            model_name='tomorrowitem',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_items', to='customers.project'),
        ),
        migrations.AddField(
            model_name='tomorrowitem',
            name='reminder_minutes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='提前提醒分钟数'),
        ),
    ]
